name: Style Guide Check of output()'s constants file
run-name: ${{ github.actor }} has triggered style guide check of output()'s constants file for the ${{ github.run_attempt }} time by initiating a ${{ github.event_name }}
on: [push, workflow_dispatch]
jobs:
  style-guide-output-util-constants:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Install Style Guide Checking Tool...
        uses: ./.github/actions/install-shfmt-via-snap
      - name: Running style guide check...
        run:  shfmt --diff --case-indent --posix ./output/util/constants.sh

