name: Style Guide Check of logging()'s Main File
run-name: ${{ github.actor }} triggered style guide check of logging()'s main.sh file for the ${{ github.run_attempt }} time by initiating a ${{ github.event_name }}
on:
  push:
    paths:
      - logging/util/main.sh
      - .github/workflows/style-guide-logging*
      - .github/actions/**/*
  workflow_dispatch:
jobs:
  style-guide-logging-util-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v4
      - name: Install Style Guide Checking Tool...
        uses: ./.github/actions/install-shfmt-on-linux
      - name: Run style guide check...
        run:  shfmt --diff --case-indent --posix ./logging/util/main.sh

