name: Unit Test output()'s createHeaderFooter() util function
run-name: ${{ github.actor }} has triggered the running of unit tests of output()'s createHeaderFooter() util function for the ${{ github.run_attempt }} time by initiating a ${{ github.event_name }}
on: [push, workflow_dispatch]
jobs:
  unit-test-ubuntu-bash-output-util-createHeaderFooter:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
#      - name: Install 'Kcov' (test coverage tool) and 'shellspec' (POSIX shell script testing tool)...
#        uses: ./.github/actions/install-kcov-and-shellspec
      - name: Install `kcov` and `shellspec` via Docker
        uses: ./.github/actions/install-kcov-and-shellspec-via-docker
      - name: Running unit tests from a 'bash' shell (with code coverage) from ${{ github.workspace }}...
        run:  shellspec --no-fail-fast -p -s /bin/bash --kcov --kcov-options "--include-pattern=output/util/createHeaderFooter.sh --limits=94,100" ./spec/unit/output/util/createHeaderFooter_*
        # TODO #53: Pipeline doesn't process --fail-low-coverage correctly.
##        run:  shellspec --no-fail-fast -p -s /bin/bash --kcov --kcov-options "--include-pattern=output/util/createHeaderFooter.sh --limits=94,100" --fail-low-coverage ./spec/unit/output/util/createHeaderFooter_*
  unit-test-ubuntu-dash-output-util-createHeaderFooter:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing 'shellspec' (POSIX shell script testing tool)...
        uses: ./.github/actions/install-shellspec
      - name: Running unit tests from a 'dash' shell...
        run:  shellspec --no-fail-fast -s /bin/dash ./spec/unit/output/util/createHeaderFooter_*
  unit-test-ubuntu-zsh-output-util-createHeaderFooter:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing 'shellspec' (POSIX shell script testing tool)...
        uses: ./.github/actions/install-shellspec
      - name: Installing 'zsh' (shell)...
        uses: ./.github/actions/install-zsh-shell-via-apt
      - name: Running unit tests from a 'zsh' shell...
        run:  shellspec --no-fail-fast -s /bin/zsh ./spec/unit/output/util/createHeaderFooter_*
  unit-test-ubuntu-ksh-output-util-createHeaderFooter:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing 'shellspec' (POSIX shell script testing tool)...
        uses: ./.github/actions/install-shellspec
      - name: Installing 'ksh' (shell)...
        uses: ./.github/actions/install-ksh-shell-via-apt-get
      - name: Running unit tests from a 'ksh' shell...
        run:  shellspec --no-fail-fast -s /bin/ksh ./spec/unit/output/util/createHeaderFooter_*
  unit-test-macos-bash-output-util-createHeaderFooter:
    runs-on: macos-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing 'shellspec' (POSIX shell script testing tool)...
        uses: ./.github/actions/install-shellspec
      - name: Running unit tests from a 'bash' shell...
        run:  $HOME/.local/bin/shellspec -s /bin/bash --no-fail-fast ./spec/unit/output/util/createHeaderFooter_*
  unit-test-macos-dash-output-util-createHeaderFooter:
    runs-on: macos-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing 'shellspec' (POSIX shell script testing tool)...
        uses: ./.github/actions/install-shellspec
      - name: Running unit tests from a 'dash' shell...
        run:  $HOME/.local/bin/shellspec -s /bin/dash --no-fail-fast ./spec/unit/output/util/createHeaderFooter_*
  unit-test-macos-zsh-output-util-createHeaderFooter:
    runs-on: macos-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing 'shellspec' (POSIX shell script testing tool)...
        uses: ./.github/actions/install-shellspec
      - name: Running unit tests from a 'zsh' shell...
        run:  $HOME/.local/bin/shellspec -s /bin/zsh --no-fail-fast ./spec/unit/output/util/createHeaderFooter_*

