name: Unit Test output()
run-name: ${{ github.actor }} has triggered testing of output() with code coverage of output() for the ${{ github.run_attempt }} time by initiating a ${{ github.event_name }}
on:
  pull_request:
    branches: [main]
    types: [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:
jobs:
  unit-test-output-zsh-ubuntu-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Install `kcov` and `shellspec` via Docker
        uses: ./.github/actions/install-kcov-and-shellspec-via-docker
      - name: Running tests of output() from a 'zsh' shell, with code coverage, from ${{ github.workspace }}...
        uses: ./.github/actions/run-shellspec
        with:
          test-path:            spec/unit/output/output_*
          shell:                /bin/zsh
          kcov-include-pattern: output/output.sh
          kcov-limit:          95
