name: Test verifyInputProvided()
run-name: ${{ github.actor }} triggered testing of verifyInputProvided() without code coverage for the ${{ github.run_attempt }} time by initiating a ${{ github.event_name }}.
on:
  push:
    paths:
      - util/verifyInputProvided/verifyInputProvided.sh
      - util/verifyInputProvided/**/*.sh
      - spec/unit/util/verifyInputProvided/verifyInputProvided_*
      - .github/workflows/**
      - .github/actions/**
  workflow_dispatch:
jobs:
  unit-test-verifyInputProvided-bash-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing ShellSpec
        uses: ./.github/actions/install-shellspec
      - name: Install bash (shell)
        id:   bash
        uses: ./.github/actions/install-shell-via-apt
        with:
          shell: bash
      # TODO: Sort out they `github.workspace` is blank.
      - name: Running tests of verifyInputProvided() from a 'bash' shell on ${{ github.workspace }}...
        uses: ./.github/actions/run-shellspec
        with:
          test-path:    ./spec/unit/util/verifyInputProvided/verifyInputProvided_*
          shell:        ${{ steps.bash.outputs.path }}
  unit-test-verifyInputProvided-dash-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing ShellSpec
        uses: ./.github/actions/install-shellspec
      - name: Install dash (shell)
        id:   dash
        uses: ./.github/actions/install-shell-via-apt
        with:
          shell: dash
      # TODO: Sort out they `github.workspace` is blank.
      - name: Running tests of verifyInputProvided() from a 'dash' shell on ${{ github.workspace }}...
        uses: ./.github/actions/run-shellspec
        with:
          test-path:    ./spec/unit/util/verifyInputProvided/verifyInputProvided_*
          shell:        ${{ steps.dash.outputs.path }}
  unit-test-verifyInputProvided-zsh-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing ShellSpec
        uses: ./.github/actions/install-shellspec
      - name: Install zsh (shell)
        id:   zsh
        uses: ./.github/actions/install-shell-via-apt
        with:
          shell: zsh
      # TODO: Sort out they `github.workspace` is blank.
      - name: Running tests of verifyInputProvided() from a 'zsh' shell on ${{ github.workspace }}...
        uses: ./.github/actions/run-shellspec
        with:
          test-path:    ./spec/unit/util/verifyInputProvided/verifyInputProvided_*
          shell:        ${{ steps.zsh.outputs.path }}
  unit-test-verifyInputProvided-bash-macos:
    runs-on: macos-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing ShellSpec...
        uses: ./.github/actions/install-shellspec
      - name: Installing bash (shell)
        id:   bash
        uses: ./.github/actions/install-shell-via-homebrew
        with:
          shell: bash
      # TODO: Sort out they `github.workspace` is blank.
      - name: Running tests of verifyInputProvided() from a 'bash' shell, with out code coverage, from ${{ github.workspace }}...
        uses: ./.github/actions/run-shellspec
        with:
          test-path:    ./spec/unit/util/verifyInputProvided/verifyInputProvided_*
          shell:        ${{ steps.bash.outputs.path }}
  unit-test-verifyInputProvided-dash-macos:
    runs-on: macos-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing ShellSpec...
        uses: ./.github/actions/install-shellspec
      - name: Installing dash (shell)
        id:   dash
        uses: ./.github/actions/install-shell-via-homebrew
        with:
          shell: dash
      # TODO: Sort out they `github.workspace` is blank.
      - name: Running tests of verifyInputProvided() from a 'dash' shell, with out code coverage, from ${{ github.workspace }}...
        uses: ./.github/actions/run-shellspec
        with:
          test-path:    ./spec/unit/util/verifyInputProvided/verifyInputProvided_*
          shell:        ${{ steps.dash.outputs.path }}
  unit-test-verifyInputProvided-zsh-macos:
    runs-on: macos-latest
    steps:
      - name: Checking out ${{ github.ref_type }} ${{ github.ref_name }} from ${{ github.repository_owner }}'s ${{ github.repository }} repo on ${{ runner.os }} because ${{ github.actor }} initiated a ${{ github.event_name }}...
        uses: actions/checkout@v3
      - name: Installing ShellSpec...
        uses: ./.github/actions/install-shellspec
      - name: Installing zsh (shell)
        id:   zsh
        uses: ./.github/actions/install-shell-via-homebrew
        with:
          shell: zsh
      # TODO: Sort out they `github.workspace` is blank.
      - name: Running tests of verifyInputProvided() from a 'zsh' shell, with out code coverage, from ${{ github.workspace }}...
        uses: ./.github/actions/run-shellspec
        with:
          test-path:    ./spec/unit/util/verifyInputProvided/verifyInputProvided_*
          shell:        ${{ steps.zsh.outputs.path }}

